### ISSUE TITLE
Support RACK_ENV for nested schedules config

### ISSUE THREAD

**Issue by stmllr** [mattyr/sidecloq#31]
Config nesting by env is supported if `Rails.env` is set. So nesting will not work in non-Rails applications.
However there are many applications which use RACK_ENV and could benefit from nested configs.
Even Rails itself uses `RACK_ENV` as a [fallback if RAILS_ENV](https://github.com/rails/rails/blob/b9ca94caea2ca6a6cc09abaffaad67b447134079/railties/lib/rails.rb#L73) is not set

**Comment by stmllr** [comment]
I tried to [create a PR](https://github.com/mattyr/sidecloq/pull/30/files) for this, by starting to add test coverage for nested configs. However the tests fail when trying to double `Rails.env`. Seems like the tests themselve depend on rails. Do you have any idea how double `Rails.env`? Alternatively I could send a PR without `Rails.env` coverage

**Comment by mattyr** [comment]
So this is a great idea, and a PR would be appreciated!

What I've done to "double" Rails.env is here:

https://github.com/mattyr/sidecloq/blob/932c9561ef644354552fb1f7994ce9fb306d0eb3/test/helper.rb#L63-L73

You can use that helper to set up a mock Rails object in your test if needed.  Just a note: we're using Rails.env instead of the env variables directly so that it will use Rails's value resolution, including that RACK_ENV fallback, automatically.  But having a fallback to RACK_ENV makes sense when Rails isn't present.

Let me know if you run into trouble, and thanks!  I'll close this with the expectation of a PR.
