### ISSUE TITLE
Ability to test schedule?

### ISSUE THREAD

**Issue by jsmestad** [mattyr/sidecloq#9]
@mattyr I am migrating from `sidetiq`, as its now deprecated, to `sidecloq`. The swap has been straightforward, however I am wondering how I can migrate our sidetiq specs to verify the same thing in sidecloq.

```ruby
  describe 'when scheduling a job' do
    it 'performs the job daily' do
      valid = Time.current.utc.beginning_of_day + 1.day
      invalid = valid + 1.day

      Timecop.freeze(Time.current.utc.beginning_of_day)

      next_occurrence = MyJob.schedule.next_occurrence

      expect(next_occurrence).to eq(valid)
      expect(next_occurrence).not_to eq(invalid)
    end
  end
```

**Comment by mattyr** [comment]
So Sidecloq takes a different approach to scheduling than Sidetiq does (did!).  Instead of attaching a schedule to the class in code, the schedule is configured externally (as I'm sure you've figured out).  So, MyJob.schedule.next_occurence isn't really valid access in the Sidecloq scope.

I can see what you're trying to test, but in some ways Sidecloq moves this from being a "functional code" thing (like Sidetiq did) to being a "configuration" thing.  IOW this becomes a test of a specific configuration rather than a test of a block of code.

So, it seems like there are two ways to view the test and how to replicate what is tested:

- Testing that parsing a daily cron line works correctly in Sidecloq.  We delegate to Rufus-Scheduler to do the schedule heavy-lifting, so you could unit test that parsing.  I'd say that if the schedules aren't being parsed correctly I'd love to get that unit test into Sidecloq itself!
- Testing that a specific configuration causes jobs to be executed as expected.  This may be more akin to an integration test, where you set up configuration and a known system state, shift the time (as you seem to be doing with Timecop), process pending jobs, and see if the system state has changed in an expected way.

Does that make sense?  Mainly the difference here is how Sidecloq's scheduler is modeled as an external trigger that causes Jobs to run, rather than having the schedules embedded in code like Sidetiq.  One advantage to this is that multiple schedule lines could include the same Job type, which means an interface like MyJob.schedule would at the very least need to be MyJob.schedule*s* (though I think it'd still be difficult to implement and a misleading interface).

I've used Sidecloq in a number of projects now and haven't felt the need to make a test like this.  But if you have an alternative suggestion, I'm definitely all ears -- i'm all about making testing easy.
